  CREATE TABLE "SYS"."GIFTCARD" 
   (	"PKGIFTCARDNO" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"FKSTATUSID" NUMBER(12,0) DEFAULT 1, 
	"CURRENTBALANCE" NUMBER(12,2) DEFAULT 0, 
	"INITIALAMOUNT" NUMBER(12,2) DEFAULT 0, 
	"FKCURRENCYID" VARCHAR2(10 BYTE) DEFAULT 'CAD' NOT NULL ENABLE, 
	"ISSUEDATE" DATE, 
	"TOPUPDATE" DATE, 
	"PIN" VARCHAR2(10 BYTE), 
	"FKGIFTCARDKINDNO" NUMBER(10,0) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;